version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg14
    container_name: hr-assistant-postgres
    environment:
      POSTGRES_USER: anhnguyen
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hr_assistant
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anhnguyen -d hr_assistant"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
